# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:
    NOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Orderer
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Store
                    - *Bank
                    - *Shipper
                    - *Port
                    - *Supplier
    NOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Store
                - *Bank
                - *Shipper
                - *Port
                - *Supplier

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Orderer
        Name: Orderer
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/codedisruptors.com/msp

    - &Store
        Name: store.comMSP
        ID: StoreMSP
        MSPDir: crypto-config/peerOrganizations/store.com/msp
        AnchorPeers:
            - Host: peer0.store.com
              Port: 7051
    - &Bank
        Name: bank.comMSP
        ID: BankMSP
        MSPDir: crypto-config/peerOrganizations/bank.com/msp
        AnchorPeers:
            - Host: peer0.bank.com
              Port: 7051
    - &Shipper
        Name: shipper.comMSP
        ID: ShipperMSP
        MSPDir: crypto-config/peerOrganizations/shipper.com/msp
        AnchorPeers:
            - Host: peer0.shipper.com
              Port: 7051
    - &Port
        Name: port.comMSP
        ID: PortMSP
        MSPDir: crypto-config/peerOrganizations/port.com/msp
        AnchorPeers:
            - Host: peer0.port.com
              Port: 7051
    - &Supplier
        Name: supplier.comMSP
        ID: SupplierMSP
        MSPDir: crypto-config/peerOrganizations/supplier.com/msp
        AnchorPeers:
            - Host: peer0.supplier.com
              Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - codedisruptors.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
