# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: codedisruptors.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Store
    Domain: store.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Bank
    Domain: bank.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Shipper
    Domain: shipper.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Port
    Domain: port.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Supplier
    Domain: supplier.com
    Template:
      Count: 2
    Users:
      Count: 1
