# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  orderer.codedisruptors.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.codedisruptors.com
    container_name: orderer.codedisruptors.com
    networks:
      - byfn

  peer0.store.com:
    container_name: peer0.store.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.store.com
    networks:
      - byfn

  peer1.store.com:
    container_name: peer1.store.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.store.com
    networks:
      - byfn

  peer0.bank.com:
    container_name: peer0.bank.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bank.com
    networks:
      - byfn

  peer1.bank.com:
    container_name: peer1.bank.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.bank.com
    networks:
      - byfn

  peer0.shipper.com:
    container_name: peer0.shipper.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.shipper.com
    networks:
      - byfn

  peer1.shipper.com:
    container_name: peer1.shipper.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.shipper.com
    networks:
      - byfn

  peer0.port.com:
    container_name: peer0.port.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.port.com
    networks:
      - byfn

  peer1.port.com:
    container_name: peer1.port.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.port.com
    networks:
      - byfn

  peer0.supplier.com:
    container_name: peer0.supplier.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.supplier.com
    networks:
      - byfn

  peer1.supplier.com:
    container_name: peer1.supplier.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.supplier.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.store.com:7051
      - CORE_PEER_LOCALMSPID=store.comMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/store.com/peers/peer0.store.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/store.com/peers/peer0.store.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/store.com/peers/peer0.store.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/store.com/users/Admin@store.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.codedisruptors.com
      - peer0.store.com
      - peer1.store.com
      - peer0.bank.com
      - peer1.bank.com
      - peer0.shipper.com
      - peer1.shipper.com
      - peer0.port.com
      - peer1.port.com
      - peer0.supplier.com
      - peer1.supplier.com
    networks:
      - byfn

