# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-store
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.store.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d4ef0d422bde27fe18c6682c8e13212596ed60d3a27aacf7991846714dc6d79d_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.store.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d4ef0d422bde27fe18c6682c8e13212596ed60d3a27aacf7991846714dc6d79d_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/store.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerStore
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-supplier
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.supplier.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.supplier.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/mightybulacs.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSupplier
    networks:
      - byfn

  peer0.store.com:
    container_name: peer0.store.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.store.com
    networks:
      - byfn

  peer1.store.com:
    container_name: peer1.store.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.store.com
    networks:
      - byfn

  peer0.bank.com:
    container_name: peer0.bank.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bank.com
    networks:
      - byfn

  peer1.bank.com:
    container_name: peer1.bank.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.bank.com
    networks:
      - byfn

  peer0.shipper.com:
    container_name: peer0.shipper.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.shipper.com
    networks:
      - byfn

  peer1.shipper.com:
    container_name: peer1.shipper.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.shipper.com
    networks:
      - byfn

  peer0.port.com:
    container_name: peer0.port.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.port.com
    networks:
      - byfn

  peer1.port.com:
    container_name: peer1.port.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.port.com
    networks:
      - byfn

  peer0.supplier.com:
    container_name: peer0.supplier.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.supplier.com
    networks:
      - byfn

  peer1.supplier.com:
    container_name: peer1.supplier.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.supplier.com
    networks:
      - byfn
